---
name: ci-pipeline # name of the workflow. This configuration will trigger the pipeline on push and pull request events, 
# set up a Windows environment with Python, install dependencies, and run tests using pytest.

on: [push, pull_request] # triggered when these actions

jobs: 
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Tests
      run: |
        pytest